
quarkus:
  http:
    root-path: /api
    test-port: 8081
    test-ssl-port: 8446
  hibernate-orm:
    database:
      generation: update
    log:
      sql: false
    persistence-xml:
      ignore: true
  mailer:
    host: ${VISA_NOTIFICATION_EMAIL_ADAPTER_HOST:capto.ill.fr}
    port: ${VISA_NOTIFICATION_EMAIL_ADAPTER_PORT:1025}

cloud:
  serverNamePrefix: ${VISA_CLOUD_SERVER_NAME_PREFIX}
  providerType: ${VISA_DEFAULT_CLOUD_PROVIDER_TYPE:'openstack'}
  providerName: ${VISA_DEFAULT_CLOUD_PROVIDER_NAME:'Default'}
  providers:
    - name: openstack
      parameters:
        identityEndpoint: ${VISA_CLOUD_IDENTITY_ENDPOINT}
        computeEndpoint: ${VISA_CLOUD_COMPUTE_ENDPOINT}
        imageEndpoint: ${VISA_CLOUD_IMAGE_ENDPOINT}
        networkEndpoint: ${VISA_CLOUD_NETWORK_ENDPOINT}
        applicationId: ${VISA_CLOUD_APPLICATION_ID}
        applicationSecret: ${VISA_CLOUD_APPLICATION_SECRET}
        addressProvider: ${VISA_CLOUD_ADDRESS_PROVIDER}
        addressProviderUUID: ${VISA_CLOUD_ADDRESS_PROVIDER_UUID}
    - name: web
      parameters:
        url: ${VISA_CLOUD_WEB_PROVIDER_URL}
        authToken: ${VISA_CLOUD_WEB_PROVIDER_AUTH_TOKEN}


business:
  numberInstanceActionThreads: 16
  instance:
    # Defaults to 14 days
    userMaxLifetimeDurationHours: ${VISA_INSTANCE_USER_MAX_LIFETIME_DURATION_HOURS:336}
    # Defaults to 60 days
    staffMaxLifetimeDurationHours: ${VISA_INSTANCE_STAFF_MAX_LIFETIME_DURATION_HOURS:1440}
    # Defaults to 4 days
    userMaxInactivityDurationHours: ${VISA_INSTANCE_USER_MAX_INACTIVITY_DURATION_HOURS:96}
    # Defaults to 8 days
    staffMaxInactivityDurationHours: ${VISA_INSTANCE_STAFF_MAX_INACTIVITY_DURATION_HOURS:192}
    defaultUserInstanceQuota: ${VISA_INSTANCE_USER_DEFAULT_QUOTA:2}
    activityRetentionPeriodDays: ${VISA_INSTANCE_ACTIVITY_RETENTION_PERIOD_DAYS:0}
  mailer:
    rootURL: ${VISA_ROOT_URL}
    enabled: ${VISA_NOTIFICATION_EMAIL_ADAPTER_ENABLED:false}
    fromEmailAddress: ${VISA_NOTIFICATION_EMAIL_ADAPTER_FROM_EMAIL_ADDRESS}
    bccEmailAddress: ${VISA_NOTIFICATION_EMAIL_ADAPTER_BCC_EMAIL_ADDRESS:}
    devEmailAddress: ${VISA_NOTIFICATION_EMAIL_ADAPTER_DEV_EMAIL_ADDRESS:}
    adminEmailAddress: ${VISA_NOTIFICATION_EMAIL_ADAPTER_ADMIN_EMAIL_ADDRESS:}
    emailTemplatesDirectory: ${VISA_NOTIFICATION_EMAIL_ADAPTER_TEMPLATES_DIRECTORY:emails/templates/}
  signature:
    privateKeyPath: ${VISA_VDI_SIGNATURE_PRIVATE_KEY_PATH}
    publicKeyPath: ${VISA_VDI_SIGNATURE_PUBLIC_KEY_PATH}
  securityGroupServiceClient:
    enabled: ${VISA_SECURITY_GROUP_SERVICE_CLIENT_ENABLED:false}
    url: ${VISA_SECURITY_GROUP_SERVICE_CLIENT_URL}
    authToken: ${VISA_SECURITY_GROUP_SERVICE_CLIENT_AUTH_TOKEN}


"%prod":
  quarkus:
    datasource:
      username: ${VISA_DATABASE_USERNAME}
      password: ${VISA_DATABASE_PASSWORD}
      jdbc:
        url: ${VISA_DATABASE_URL}
      db-kind: postgresql
      devservices:
        enabled: false
    log:
      category:
        "eu.ill":
          level: DEBUG

"%dev":
  quarkus:
    datasource:
      username: ${VISA_DATABASE_USERNAME}
      password: ${VISA_DATABASE_PASSWORD}
      jdbc:
        url: ${VISA_DATABASE_URL}
      db-kind: postgresql
      devservices:
        enabled: false
    log:
      category:
        "eu.ill":
          level: DEBUG

"%test":
  quarkus:
    scheduler:
      enabled: false
    log:
      level: info
    hibernate-orm:
      log:
        sql: false
      database:
        generation: create
      sql-load-script: fixtures.sql
      persistence-xml:
        ignore: true
    datasource:
      devservices:
        enabled: true
    mailer:
      mock: true
    devservices:
      timeout: 5m

